# Copyright © 2026 Ligandal, Inc. All rights reserved.
"""
19 — MSA generation, memory store, reports, diseases catalog.

Covers the smaller resources that don't need their own example file:
  client.msa.generate(sequences, gene)
  client.memory.save / .list / .search / .recent_activity / .delete
  client.reports.generate / .download
  client.diseases.search / .get / .categories / .mutations / .gene_mutations

Run with:
    LIGANDAI_API_KEY=lgai_pro_... python 19_msa_memory_reports_diseases.py
"""

from __future__ import annotations

import os
import sys
from pathlib import Path

from ligandai import LigandAI
from ligandai.errors import LigandAIError


def main() -> int:
    key = os.environ.get("LIGANDAI_API_KEY")
    if not key:
        print("LIGANDAI_API_KEY env var is required", file=sys.stderr)
        return 1

    client = LigandAI(api_key=key)
    out_dir = Path(os.environ.get("LIGANDAI_OUT_DIR", "/tmp/ligandai_outputs"))
    out_dir.mkdir(parents=True, exist_ok=True)

    try:
        # 1) MSA generation for a target receptor
        print("== msa.generate(sequences={'A': 'EGFR sequence...'}) ==")
        sequences = {
            "A": "MRPSGTAGAALLALLAALCPASRAAAA"
                 "EAYVEKVTSPDLATCNNLPYYHITQECVTACSAR",
        }
        try:
            msa = client.msa.generate(sequences=sequences, gene="EGFR")
            print(f"  msa_id={msa.id}  num_sequences={msa.num_sequences}  "
                  f"depth={msa.depth}")
        except LigandAIError as e:
            print(f"  (msa.generate skipped: {e})")

        # 2) Memory store — save a research note
        print("\n== memory.save(content='example note', memory_type='research_note') ==")
        try:
            note = client.memory.save(
                content="Example: generated 50 binders for EGFR with hotspots [60, 62].",
                memory_type="research_note",
                title="SDK example #19",
                tags=["example", "egfr"],
            )
            print(f"  saved id={note.id}")

            # List + search round-trip
            recent = client.memory.list(limit=3)
            print(f"\n  memory.list(limit=3): {len(recent)} entries")
            hits = client.memory.search("egfr", memory_type="research_note", limit=3)
            print(f"  memory.search('egfr'): {len(hits)} matches")
        except LigandAIError as e:
            print(f"  (memory ops skipped: {e})")

        # 3) Recent activity
        print("\n== memory.recent_activity(limit=3) ==")
        try:
            act = client.memory.recent_activity(limit=3)
            print(f"  total events: {act.total_count}")
            for e in act.events[:3]:
                print(f"    - {e.event_type}: {e.summary[:60]}")
        except LigandAIError as e:
            print(f"  (recent_activity skipped: {e})")

        # 4) Diseases catalog
        print("\n== diseases.search('osteosarcoma') ==")
        try:
            diseases = client.diseases.search("osteosarcoma")
            for d in diseases[:3]:
                print(f"  - id={d.id}  name={d.name}  category={d.category}")

            if diseases:
                muts = client.diseases.gene_mutations(diseases[0].name)
                print(f"\n  gene_mutations: {len(muts)} known")
        except LigandAIError as e:
            print(f"  (diseases skipped: {e})")

        # 5) Report generation (asynchronous; just demonstrate the call shape)
        print("\n== reports.generate(title='Example Report', sections=[...]) ==")
        try:
            report = client.reports.generate(
                title="SDK Example Report",
                sections=[
                    {"type": "header", "text": "Example summary"},
                    {"type": "text", "content": "Generated by examples/19."},
                ],
                report_type="custom",
            )
            print(f"  report_id={report.id}  status={report.status}")
            # Download once ready (poll status if needed):
            # outfile = client.reports.download(report.id, dest=out_dir / 'report.pdf')
        except LigandAIError as e:
            print(f"  (reports skipped: {e})")

    except LigandAIError as e:
        print(f"API error: {type(e).__name__}: {e}", file=sys.stderr)
        return 2

    return 0


if __name__ == "__main__":
    sys.exit(main())
